dl:
	mkdir -p Dockerfile/php
	mkdir -p Dockerfile/php/extensions
	mkdir -p Dockerfile/redis
	mkdir -p Dockerfile/nginx
	wget http://cn2.php.net/get/php-7.0.9.tar.gz/from/this/mirror -O Dockerfile/php/php.tar.gz
	wget http://pecl.php.net/get/redis-3.0.0.tgz -O Dockerfile/php/extensions/redis.tgz
	wget http://pecl.php.net/get/xdebug-2.4.0.tgz -O Dockerfile/php/extensions/xdebug.tgz
	wget http://pecl.php.net/get/mongodb-1.1.8.tgz -O Dockerfile/php/extensions/mongodb.tgz
	wget http://download.redis.io/releases/redis-3.2.3.tar.gz -O Dockerfile/redis/redis.tar.gz
	wget https://nginx.org/download/nginx-1.10.1.tar.gz -O Dockerfile/nginx/nginx.tar.gz

