dl:
	mkdir -p ./Dockerfiles/php/extensions
	wget http://pecl.php.net/get/redis-3.0.0.tgz -O ./Dockerfiles/php/extensions/redis.tgz
	wget http://pecl.php.net/get/xdebug-2.4.0.tgz -O ./Dockerfiles/php/extensions/xdebug.tgz
	wget http://pecl.php.net/get/mongodb-1.1.8.tgz -O ./Dockerfiles/php/extensions/mongodb.tgz
	wget http://pecl.php.net/get/swoole-1.8.12.tgz -O ./Dockerfiles/php/extensions/swoole.tgz
