FROM php:7.0-fpm

ADD sources.list /etc/apt/sources.list

RUN apt-get update && apt-get install -y \
        libssl-dev \
	libmcrypt-dev \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng12-dev \
	&& rm -r /var/lib/apt/lists/*

# 安装 php 扩展
COPY extensions/redis.tgz /home/redis.tgz
COPY extensions/mongodb.tgz /home/mongodb.tgz
COPY extensions/xdebug.tgz /home/xdebug.tgz

RUN docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \

        && docker-php-ext-install zip \
        && docker-php-ext-install gd \
        && docker-php-ext-install mbstring \
        && docker-php-ext-install mcrypt \
        && docker-php-ext-install pdo_mysql \
	&& docker-php-ext-install mysqli

RUN pecl install /home/redis.tgz && echo "extension=redis.so" > /usr/local/etc/php/conf.d/redis.ini \
        && pecl install /home/mongodb.tgz && echo "extension=mongodb.so" > /usr/local/etc/php/conf.d/mongodb.ini \
        && pecl install /home/xdebug.tgz && echo "zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20151012/xdebug.so" > /usr/local/etc/php/conf.d/xdebug.ini

# PHP config
# ADD php.ini    /usr/local/etc/php/php.ini
# ADD php-fpm.conf    /usr/local/etc/php-fpm.conf

# Composer
# ADD composer.phar /usr/local/bin/composer
# RUN chmod 755 /usr/local/bin/composer

EXPOSE 9000
