dev_nginx:
    build: ./nginx
    container_name: dev_nginx
    ports:
        - "80:80"
    links:
        - "dev_php"
    volumes:
        - ../opt/config/nginx/sites-enabled:/etc/nginx/sites-enabled
        - ../opt/log/nginx:/opt/log/nginx
        - ../opt/www:/opt/www

dev_php:
    build: ./php
    container_name: dev_php
    ports:
        - "9000:9000"
    links:
        - "dev_mysql"
        - "dev_redis"
        - "dev_mongo"
    volumes:
        - ../opt/www:/opt/www

dev_mysql:
    build: ./mysql
    container_name: dev_mysql
    ports:
        - "3306:3306"
    volumes:
        - ../opt/data/mysql:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: testmysql

dev_mongo:
    build: ./mongo
    container_name: dev_mongo
    ports:
        - "27017:27017"
    volumes:
        - ../opt/data/mongodb:/var/lib/mongodb
    command: --auth

dev_redis:
    build: ./redis
    container_name: dev_redis
    ports:
        - "6379:6379"



